### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'strike'

### ISSUE THREAD

**Issue by abitrolly** [jonathanslenders/pypager#19]
```bash
$  pip install pypager
Collecting pypager
  Downloading pypager-3.0.0-py3-none-any.whl (18 kB)
Requirement already satisfied: pygments in /usr/local/lib/python3.9/site-packages (from pypager) (2.10.0)
Collecting prompt-toolkit<3.1.0,>=3.0.0
  Downloading prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)
     |████████████████████████████████| 370 kB 2.1 MB/s 
Requirement already satisfied: wcwidth in /usr/local/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.0->pypager) (0.2.5)
Installing collected packages: prompt-toolkit, pypager
Successfully installed prompt-toolkit-3.0.20 pypager-3.0.0
```

```python
$ pypager 1
Traceback (most recent call last):
  File "/usr/local/bin/pypager", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/pypager/entry_points/run_pypager.py", line 49, in run
    pager.add_source(FileSource(filename, lexer=lexer))
  File "/usr/local/lib/python3.9/site-packages/pypager/source.py", line 327, in __init__
    super().__init__(self.fp.fileno(), lexer=lexer, name=filename)
  File "/usr/local/lib/python3.9/site-packages/pypager/source.py", line 86, in __init__
    self._attrs = Attrs(
TypeError: <lambda>() missing 1 required positional argument: 'strike'
```

**Comment by wasi-master** [comment]
I am also getting a simillar error with the same traceback

```python
TypeError: __new__() missing 1 required positional argument: 'strike'
```

Edit after switching to Windows 11 I'm now getting the exact same error

**Comment by TechWiz-3** [comment]
Same
